#!/bin/bash
#    
# Look ActiveMQ Logs v1.0 (name file using as autocomplete for dev_manage too)
# 
# GlowByte, v1.0, 03.2019
# 

# Parsing args
serv=''
flg_after=0
before_=""
_after=""
for arg in "$@"
do
    if [ "$arg" = "log" ]; then
        flg_after=$(($flg_after + 1))
        serv="$arg"
        continue
    fi
    if [ $flg_after -eq 0 ]; then
        before_="$before_ $arg"
    else
        _after="$_after $arg"
    fi
done
if [ $flg_after -gt 1 ]; then
    echo "------------------------------------------"
    echo "ERROR: several 'log' arguments specified!"
    echo "------------------------------------------"
    exit 1
fi

# Look log
case $serv in
log)
    echo "--------------------------------------------------------------------------"
    if [ ! -z "$before_" ]; then
        echo "INFO COMMAND: $before_ /sas/apache-activemq-5.15.2/data/activemq.log $_after"
        echo "--------------------------------------------------------------------------"
        ${before_} /sas/apache-activemq-5.15.2/data/activemq.log ${_after}
    else
        tac /sas/apache-activemq-5.15.2/data/activemq.log | less
    fi
    ;;
*)
    echo "----------------------- INFO -----------------------"
    echo "Look ActiveMQ Logs v1.0"
    echo "----------------------------------------------------"
    echo "Usage ./mq [cmd] log [cmd]                    "
    echo
    echo "cmd       - commands before or after log file "
    echo "log       - ActiveMQ log file                 "
    echo "----------------------------------------------------"

    ;;
esac

